/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SoftDev;

/**
 *
 * @author b_kotsana
 */
public class entertainment extends javax.swing.JFrame {

    /**
     * Creates new form entertainment
     */
    public entertainment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        checkbox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox1.setLabel("Restaurants ");
        jPanel1.add(checkbox1);
        checkbox1.setBounds(40, 130, 120, 40);

        checkbox2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox2.setLabel("Coffee Shops");
        jPanel1.add(checkbox2);
        checkbox2.setBounds(40, 310, 120, 40);

        checkbox3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox3.setLabel("Bars");
        jPanel1.add(checkbox3);
        checkbox3.setBounds(40, 190, 120, 40);

        checkbox4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox4.setLabel("Cinema");
        jPanel1.add(checkbox4);
        checkbox4.setBounds(40, 250, 120, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Show Map");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 470, 150, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 460, 160, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_15.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 100, 340, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 180, 190, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ENTERTAIMENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 20, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(checkbox1.getState());
    if((checkbox1.getState()==true) && (checkbox2.getState()==false)  && (checkbox3.getState()==false) && (checkbox4.getState()==false) ){
       
      dispose();
      RestImage a= new RestImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
    if(checkbox1.getState()==false && checkbox2.getState()==true  && checkbox3.getState()==false && checkbox4.getState()==false ){
          dispose();
        CoffeeImage a= new CoffeeImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
                          
    }
    if(checkbox1.getState()==false && checkbox2.getState()==false  && checkbox3.getState()==true && checkbox4.getState()==false ){
    
      dispose(); 
      BarsImage a= new BarsImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        
        }
    if(checkbox1.getState()==false && checkbox2.getState()==false  && checkbox3.getState()==false && checkbox4.getState()==true ){
      dispose();
      CinemaImage a= new CinemaImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
    
     if(checkbox1.getState()==true && checkbox2.getState()==false  && checkbox3.getState()==false && checkbox4.getState()==true ){
      dispose();
      RCImage a= new RCImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
     
     if(checkbox1.getState()==false && checkbox2.getState()==false  && checkbox3.getState()==true && checkbox4.getState()==true ){
      dispose();
      BCImage a= new BCImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
     
      if(checkbox1.getState()==false && checkbox2.getState()==true  && checkbox3.getState()==false && checkbox4.getState()==true ){
      dispose();
      CImage a= new CImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
        
      
      if(checkbox1.getState()==false && checkbox2.getState()==true  && checkbox3.getState()==true && checkbox4.getState()==false ){
      dispose();
      CofbImage a= new CofbImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
      
        if(checkbox1.getState()==true && checkbox2.getState()==false  && checkbox3.getState()==true && checkbox4.getState()==false ){
      dispose();
      RBImage a= new RBImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
        
        
        
       if(checkbox1.getState()==true && checkbox2.getState()==true  && checkbox3.getState()==false && checkbox4.getState()==false ){
      dispose();
      RcofImage a= new RcofImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
       
        if(checkbox1.getState()==true && checkbox2.getState()==true  && checkbox3.getState()==true && checkbox4.getState()==false ){
      dispose();
      RcofbarImage a= new  RcofbarImage(); 
      a.pack();//here
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
        
         if(checkbox1.getState()==true && checkbox2.getState()==true  && checkbox3.getState()==false && checkbox4.getState()==true ){
      dispose();
      RcofcinImage a= new  RcofcinImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
         
          if(checkbox1.getState()==true && checkbox2.getState()==false  && checkbox3.getState()==true && checkbox4.getState()==true ){
      dispose();
      RbarcinImage a= new RbarcinImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
          
        if(checkbox1.getState()==false && checkbox2.getState()==true  && checkbox3.getState()==true && checkbox4.getState()==true ){
      dispose();
      BarcofcinImage a= new BarcofcinImage(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
        if(checkbox1.getState()==true && checkbox2.getState()==true  && checkbox3.getState()==true && checkbox4.getState()==true ){
      dispose();
      all a= new all(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            dispose();
      CityInfo a= new CityInfo(); 
      a.pack();
      a.setLocationRelativeTo(null);
      a.setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entertainment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
